# To generate the client:
# npx @openapitools/openapi-generator-cli generate -c openapi-dotnet.yaml

inputSpec: api-yaml/openapi.yaml
generatorName: csharp
outputDir: generated/
packageName: MangaUpdates
packageVersion: 1.0.0
targetFramework: net6.0
typeMappings:
 - integer=long