/*
 * MangaUpdates API
 *
 * This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MangaUpdates.Client.OpenAPIDateConverter;

namespace MangaUpdates.Model
{
    /// <summary>
    /// AboutusUserModelV1
    /// </summary>
    [DataContract(Name = "AboutusUserModelV1")]
    public partial class AboutusUserModelV1 : IEquatable<AboutusUserModelV1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AboutusUserModelV1" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AboutusUserModelV1() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AboutusUserModelV1" /> class.
        /// </summary>
        /// <param name="entryId">entryId (required).</param>
        /// <param name="position">position.</param>
        /// <param name="username">username.</param>
        /// <param name="userId">userId.</param>
        public AboutusUserModelV1(long entryId = default(long), long position = default(long), string username = default(string), long userId = default(long))
        {
            this.EntryId = entryId;
            this.Position = position;
            this.Username = username;
            this.UserId = userId;
        }

        /// <summary>
        /// Gets or Sets EntryId
        /// </summary>
        [DataMember(Name = "entry_id", IsRequired = true, EmitDefaultValue = true)]
        public long EntryId { get; set; }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", EmitDefaultValue = false)]
        public long Position { get; set; }

        /// <summary>
        /// Gets or Sets Username
        /// </summary>
        [DataMember(Name = "username", EmitDefaultValue = false)]
        public string Username { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [DataMember(Name = "user_id", EmitDefaultValue = false)]
        public long UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AboutusUserModelV1 {\n");
            sb.Append("  EntryId: ").Append(EntryId).Append("\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AboutusUserModelV1);
        }

        /// <summary>
        /// Returns true if AboutusUserModelV1 instances are equal
        /// </summary>
        /// <param name="input">Instance of AboutusUserModelV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AboutusUserModelV1 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.EntryId == input.EntryId ||
                    this.EntryId.Equals(input.EntryId)
                ) && 
                (
                    this.Position == input.Position ||
                    this.Position.Equals(input.Position)
                ) && 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                ) && 
                (
                    this.UserId == input.UserId ||
                    this.UserId.Equals(input.UserId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.EntryId.GetHashCode();
                hashCode = (hashCode * 59) + this.Position.GetHashCode();
                if (this.Username != null)
                {
                    hashCode = (hashCode * 59) + this.Username.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
