/*
 * MangaUpdates API
 *
 * This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MangaUpdates.Client.OpenAPIDateConverter;

namespace MangaUpdates.Model
{
    /// <summary>
    /// AuthorsModelUpdateV1
    /// </summary>
    [DataContract(Name = "AuthorsModelUpdateV1")]
    public partial class AuthorsModelUpdateV1 : IEquatable<AuthorsModelUpdateV1>, IValidatableObject
    {
        /// <summary>
        /// Defines Bloodtype
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum BloodtypeEnum
        {
            /// <summary>
            /// Enum NA for value: N/A
            /// </summary>
            [EnumMember(Value = "N/A")]
            NA = 1,

            /// <summary>
            /// Enum A for value: A
            /// </summary>
            [EnumMember(Value = "A")]
            A = 2,

            /// <summary>
            /// Enum B for value: B
            /// </summary>
            [EnumMember(Value = "B")]
            B = 3,

            /// <summary>
            /// Enum AB for value: AB
            /// </summary>
            [EnumMember(Value = "AB")]
            AB = 4,

            /// <summary>
            /// Enum O for value: O
            /// </summary>
            [EnumMember(Value = "O")]
            O = 5

        }


        /// <summary>
        /// Gets or Sets Bloodtype
        /// </summary>
        [DataMember(Name = "bloodtype", EmitDefaultValue = false)]
        public BloodtypeEnum? Bloodtype { get; set; }
        /// <summary>
        /// Defines Gender
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum GenderEnum
        {
            /// <summary>
            /// Enum NA for value: N/A
            /// </summary>
            [EnumMember(Value = "N/A")]
            NA = 1,

            /// <summary>
            /// Enum Male for value: Male
            /// </summary>
            [EnumMember(Value = "Male")]
            Male = 2,

            /// <summary>
            /// Enum Female for value: Female
            /// </summary>
            [EnumMember(Value = "Female")]
            Female = 3,

            /// <summary>
            /// Enum Other for value: Other
            /// </summary>
            [EnumMember(Value = "Other")]
            Other = 4

        }


        /// <summary>
        /// Gets or Sets Gender
        /// </summary>
        [DataMember(Name = "gender", EmitDefaultValue = false)]
        public GenderEnum? Gender { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorsModelUpdateV1" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="associated">associated.</param>
        /// <param name="actualname">actualname.</param>
        /// <param name="birthday">birthday.</param>
        /// <param name="birthplace">birthplace.</param>
        /// <param name="bloodtype">bloodtype.</param>
        /// <param name="gender">gender.</param>
        /// <param name="social">social.</param>
        /// <param name="comments">comments.</param>
        /// <param name="admin">admin.</param>
        public AuthorsModelUpdateV1(string name = default(string), List<AuthorsModelUpdateV1Associated> associated = default(List<AuthorsModelUpdateV1Associated>), string actualname = default(string), BirthdayModelV1 birthday = default(BirthdayModelV1), string birthplace = default(string), BloodtypeEnum? bloodtype = default(BloodtypeEnum?), GenderEnum? gender = default(GenderEnum?), AuthorsModelUpdateV1Social social = default(AuthorsModelUpdateV1Social), string comments = default(string), AuthorsModelUpdateV1Admin admin = default(AuthorsModelUpdateV1Admin))
        {
            this.Name = name;
            this.Associated = associated;
            this.Actualname = actualname;
            this.Birthday = birthday;
            this.Birthplace = birthplace;
            this.Bloodtype = bloodtype;
            this.Gender = gender;
            this.Social = social;
            this.Comments = comments;
            this.Admin = admin;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Associated
        /// </summary>
        [DataMember(Name = "associated", EmitDefaultValue = false)]
        public List<AuthorsModelUpdateV1Associated> Associated { get; set; }

        /// <summary>
        /// Gets or Sets Actualname
        /// </summary>
        [DataMember(Name = "actualname", EmitDefaultValue = false)]
        public string Actualname { get; set; }

        /// <summary>
        /// Gets or Sets Birthday
        /// </summary>
        [DataMember(Name = "birthday", EmitDefaultValue = false)]
        public BirthdayModelV1 Birthday { get; set; }

        /// <summary>
        /// Gets or Sets Birthplace
        /// </summary>
        [DataMember(Name = "birthplace", EmitDefaultValue = false)]
        public string Birthplace { get; set; }

        /// <summary>
        /// Gets or Sets Social
        /// </summary>
        [DataMember(Name = "social", EmitDefaultValue = false)]
        public AuthorsModelUpdateV1Social Social { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name = "comments", EmitDefaultValue = false)]
        public string Comments { get; set; }

        /// <summary>
        /// Gets or Sets Admin
        /// </summary>
        [DataMember(Name = "admin", EmitDefaultValue = false)]
        public AuthorsModelUpdateV1Admin Admin { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthorsModelUpdateV1 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Associated: ").Append(Associated).Append("\n");
            sb.Append("  Actualname: ").Append(Actualname).Append("\n");
            sb.Append("  Birthday: ").Append(Birthday).Append("\n");
            sb.Append("  Birthplace: ").Append(Birthplace).Append("\n");
            sb.Append("  Bloodtype: ").Append(Bloodtype).Append("\n");
            sb.Append("  Gender: ").Append(Gender).Append("\n");
            sb.Append("  Social: ").Append(Social).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  Admin: ").Append(Admin).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthorsModelUpdateV1);
        }

        /// <summary>
        /// Returns true if AuthorsModelUpdateV1 instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthorsModelUpdateV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthorsModelUpdateV1 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Associated == input.Associated ||
                    this.Associated != null &&
                    input.Associated != null &&
                    this.Associated.SequenceEqual(input.Associated)
                ) && 
                (
                    this.Actualname == input.Actualname ||
                    (this.Actualname != null &&
                    this.Actualname.Equals(input.Actualname))
                ) && 
                (
                    this.Birthday == input.Birthday ||
                    (this.Birthday != null &&
                    this.Birthday.Equals(input.Birthday))
                ) && 
                (
                    this.Birthplace == input.Birthplace ||
                    (this.Birthplace != null &&
                    this.Birthplace.Equals(input.Birthplace))
                ) && 
                (
                    this.Bloodtype == input.Bloodtype ||
                    this.Bloodtype.Equals(input.Bloodtype)
                ) && 
                (
                    this.Gender == input.Gender ||
                    this.Gender.Equals(input.Gender)
                ) && 
                (
                    this.Social == input.Social ||
                    (this.Social != null &&
                    this.Social.Equals(input.Social))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.Admin == input.Admin ||
                    (this.Admin != null &&
                    this.Admin.Equals(input.Admin))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Associated != null)
                {
                    hashCode = (hashCode * 59) + this.Associated.GetHashCode();
                }
                if (this.Actualname != null)
                {
                    hashCode = (hashCode * 59) + this.Actualname.GetHashCode();
                }
                if (this.Birthday != null)
                {
                    hashCode = (hashCode * 59) + this.Birthday.GetHashCode();
                }
                if (this.Birthplace != null)
                {
                    hashCode = (hashCode * 59) + this.Birthplace.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Bloodtype.GetHashCode();
                hashCode = (hashCode * 59) + this.Gender.GetHashCode();
                if (this.Social != null)
                {
                    hashCode = (hashCode * 59) + this.Social.GetHashCode();
                }
                if (this.Comments != null)
                {
                    hashCode = (hashCode * 59) + this.Comments.GetHashCode();
                }
                if (this.Admin != null)
                {
                    hashCode = (hashCode * 59) + this.Admin.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
