/*
 * MangaUpdates API
 *
 * This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MangaUpdates.Client.OpenAPIDateConverter;

namespace MangaUpdates.Model
{
    /// <summary>
    /// ForumSearchResponseV1
    /// </summary>
    [DataContract(Name = "ForumSearchResponseV1")]
    public partial class ForumSearchResponseV1 : IEquatable<ForumSearchResponseV1>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ForumSearchResponseV1" /> class.
        /// </summary>
        /// <param name="totalHits">totalHits.</param>
        /// <param name="page">page.</param>
        /// <param name="perPage">perPage.</param>
        /// <param name="topicResults">topicResults.</param>
        /// <param name="postResults">postResults.</param>
        public ForumSearchResponseV1(long totalHits = default(long), long page = default(long), long perPage = default(long), List<ForumSearchResponseV1TopicResults> topicResults = default(List<ForumSearchResponseV1TopicResults>), List<ForumSearchResponseV1PostResults> postResults = default(List<ForumSearchResponseV1PostResults>))
        {
            this.TotalHits = totalHits;
            this.Page = page;
            this.PerPage = perPage;
            this.TopicResults = topicResults;
            this.PostResults = postResults;
        }

        /// <summary>
        /// Gets or Sets TotalHits
        /// </summary>
        [DataMember(Name = "total_hits", EmitDefaultValue = false)]
        public long TotalHits { get; set; }

        /// <summary>
        /// Gets or Sets Page
        /// </summary>
        [DataMember(Name = "page", EmitDefaultValue = false)]
        public long Page { get; set; }

        /// <summary>
        /// Gets or Sets PerPage
        /// </summary>
        [DataMember(Name = "per_page", EmitDefaultValue = false)]
        public long PerPage { get; set; }

        /// <summary>
        /// Gets or Sets TopicResults
        /// </summary>
        [DataMember(Name = "topic_results", EmitDefaultValue = false)]
        public List<ForumSearchResponseV1TopicResults> TopicResults { get; set; }

        /// <summary>
        /// Gets or Sets PostResults
        /// </summary>
        [DataMember(Name = "post_results", EmitDefaultValue = false)]
        public List<ForumSearchResponseV1PostResults> PostResults { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ForumSearchResponseV1 {\n");
            sb.Append("  TotalHits: ").Append(TotalHits).Append("\n");
            sb.Append("  Page: ").Append(Page).Append("\n");
            sb.Append("  PerPage: ").Append(PerPage).Append("\n");
            sb.Append("  TopicResults: ").Append(TopicResults).Append("\n");
            sb.Append("  PostResults: ").Append(PostResults).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ForumSearchResponseV1);
        }

        /// <summary>
        /// Returns true if ForumSearchResponseV1 instances are equal
        /// </summary>
        /// <param name="input">Instance of ForumSearchResponseV1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ForumSearchResponseV1 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.TotalHits == input.TotalHits ||
                    this.TotalHits.Equals(input.TotalHits)
                ) && 
                (
                    this.Page == input.Page ||
                    this.Page.Equals(input.Page)
                ) && 
                (
                    this.PerPage == input.PerPage ||
                    this.PerPage.Equals(input.PerPage)
                ) && 
                (
                    this.TopicResults == input.TopicResults ||
                    this.TopicResults != null &&
                    input.TopicResults != null &&
                    this.TopicResults.SequenceEqual(input.TopicResults)
                ) && 
                (
                    this.PostResults == input.PostResults ||
                    this.PostResults != null &&
                    input.PostResults != null &&
                    this.PostResults.SequenceEqual(input.PostResults)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.TotalHits.GetHashCode();
                hashCode = (hashCode * 59) + this.Page.GetHashCode();
                hashCode = (hashCode * 59) + this.PerPage.GetHashCode();
                if (this.TopicResults != null)
                {
                    hashCode = (hashCode * 59) + this.TopicResults.GetHashCode();
                }
                if (this.PostResults != null)
                {
                    hashCode = (hashCode * 59) + this.PostResults.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
