/*
 * MangaUpdates API
 *
 * This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MangaUpdates.Client.OpenAPIDateConverter;

namespace MangaUpdates.Model
{
    /// <summary>
    /// MiscOnlineUsersModelV1UsersMetadata
    /// </summary>
    [DataContract(Name = "MiscOnlineUsersModelV1UsersMetadata")]
    public partial class MiscOnlineUsersModelV1UsersMetadata : IEquatable<MiscOnlineUsersModelV1UsersMetadata>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MiscOnlineUsersModelV1UsersMetadata" /> class.
        /// </summary>
        /// <param name="lastActive">lastActive.</param>
        /// <param name="invisible">invisible.</param>
        /// <param name="superModerator">superModerator.</param>
        public MiscOnlineUsersModelV1UsersMetadata(TimeV1 lastActive = default(TimeV1), bool invisible = default(bool), bool superModerator = default(bool))
        {
            this.LastActive = lastActive;
            this.Invisible = invisible;
            this.SuperModerator = superModerator;
        }

        /// <summary>
        /// Gets or Sets LastActive
        /// </summary>
        [DataMember(Name = "last_active", EmitDefaultValue = false)]
        public TimeV1 LastActive { get; set; }

        /// <summary>
        /// Gets or Sets Invisible
        /// </summary>
        [DataMember(Name = "invisible", EmitDefaultValue = true)]
        public bool Invisible { get; set; }

        /// <summary>
        /// Gets or Sets SuperModerator
        /// </summary>
        [DataMember(Name = "super_moderator", EmitDefaultValue = true)]
        public bool SuperModerator { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MiscOnlineUsersModelV1UsersMetadata {\n");
            sb.Append("  LastActive: ").Append(LastActive).Append("\n");
            sb.Append("  Invisible: ").Append(Invisible).Append("\n");
            sb.Append("  SuperModerator: ").Append(SuperModerator).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MiscOnlineUsersModelV1UsersMetadata);
        }

        /// <summary>
        /// Returns true if MiscOnlineUsersModelV1UsersMetadata instances are equal
        /// </summary>
        /// <param name="input">Instance of MiscOnlineUsersModelV1UsersMetadata to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MiscOnlineUsersModelV1UsersMetadata input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.LastActive == input.LastActive ||
                    (this.LastActive != null &&
                    this.LastActive.Equals(input.LastActive))
                ) && 
                (
                    this.Invisible == input.Invisible ||
                    this.Invisible.Equals(input.Invisible)
                ) && 
                (
                    this.SuperModerator == input.SuperModerator ||
                    this.SuperModerator.Equals(input.SuperModerator)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LastActive != null)
                {
                    hashCode = (hashCode * 59) + this.LastActive.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Invisible.GetHashCode();
                hashCode = (hashCode * 59) + this.SuperModerator.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
