/*
 * MangaUpdates API
 *
 * This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MangaUpdates.Client.OpenAPIDateConverter;

namespace MangaUpdates.Model
{
    /// <summary>
    /// SeriesModelSearchV1Rank
    /// </summary>
    [DataContract(Name = "SeriesModelSearchV1Rank")]
    public partial class SeriesModelSearchV1Rank : IEquatable<SeriesModelSearchV1Rank>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeriesModelSearchV1Rank" /> class.
        /// </summary>
        /// <param name="position">position.</param>
        /// <param name="oldPosition">oldPosition.</param>
        /// <param name="lists">lists.</param>
        public SeriesModelSearchV1Rank(SeriesModelSearchV1RankPosition position = default(SeriesModelSearchV1RankPosition), SeriesModelSearchV1RankOldPosition oldPosition = default(SeriesModelSearchV1RankOldPosition), SeriesModelSearchV1RankLists lists = default(SeriesModelSearchV1RankLists))
        {
            this.Position = position;
            this.OldPosition = oldPosition;
            this.Lists = lists;
        }

        /// <summary>
        /// Gets or Sets Position
        /// </summary>
        [DataMember(Name = "position", EmitDefaultValue = false)]
        public SeriesModelSearchV1RankPosition Position { get; set; }

        /// <summary>
        /// Gets or Sets OldPosition
        /// </summary>
        [DataMember(Name = "old_position", EmitDefaultValue = false)]
        public SeriesModelSearchV1RankOldPosition OldPosition { get; set; }

        /// <summary>
        /// Gets or Sets Lists
        /// </summary>
        [DataMember(Name = "lists", EmitDefaultValue = false)]
        public SeriesModelSearchV1RankLists Lists { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SeriesModelSearchV1Rank {\n");
            sb.Append("  Position: ").Append(Position).Append("\n");
            sb.Append("  OldPosition: ").Append(OldPosition).Append("\n");
            sb.Append("  Lists: ").Append(Lists).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SeriesModelSearchV1Rank);
        }

        /// <summary>
        /// Returns true if SeriesModelSearchV1Rank instances are equal
        /// </summary>
        /// <param name="input">Instance of SeriesModelSearchV1Rank to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SeriesModelSearchV1Rank input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Position == input.Position ||
                    (this.Position != null &&
                    this.Position.Equals(input.Position))
                ) && 
                (
                    this.OldPosition == input.OldPosition ||
                    (this.OldPosition != null &&
                    this.OldPosition.Equals(input.OldPosition))
                ) && 
                (
                    this.Lists == input.Lists ||
                    (this.Lists != null &&
                    this.Lists.Equals(input.Lists))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Position != null)
                {
                    hashCode = (hashCode * 59) + this.Position.GetHashCode();
                }
                if (this.OldPosition != null)
                {
                    hashCode = (hashCode * 59) + this.OldPosition.GetHashCode();
                }
                if (this.Lists != null)
                {
                    hashCode = (hashCode * 59) + this.Lists.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
