/*
 * MangaUpdates API
 *
 * This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MangaUpdates.Model;
using MangaUpdates.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MangaUpdates.Test.Model
{
    /// <summary>
    ///  Class for testing AuthorsModelV1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthorsModelV1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthorsModelV1
        //private AuthorsModelV1 instance;

        public AuthorsModelV1Tests()
        {
            // TODO uncomment below to create an instance of AuthorsModelV1
            //instance = new AuthorsModelV1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthorsModelV1
        /// </summary>
        [Fact]
        public void AuthorsModelV1InstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthorsModelV1
            //Assert.IsType<AuthorsModelV1>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'Associated'
        /// </summary>
        [Fact]
        public void AssociatedTest()
        {
            // TODO unit test for the property 'Associated'
        }
        /// <summary>
        /// Test the property 'Image'
        /// </summary>
        [Fact]
        public void ImageTest()
        {
            // TODO unit test for the property 'Image'
        }
        /// <summary>
        /// Test the property 'Actualname'
        /// </summary>
        [Fact]
        public void ActualnameTest()
        {
            // TODO unit test for the property 'Actualname'
        }
        /// <summary>
        /// Test the property 'Birthday'
        /// </summary>
        [Fact]
        public void BirthdayTest()
        {
            // TODO unit test for the property 'Birthday'
        }
        /// <summary>
        /// Test the property 'Birthplace'
        /// </summary>
        [Fact]
        public void BirthplaceTest()
        {
            // TODO unit test for the property 'Birthplace'
        }
        /// <summary>
        /// Test the property 'Bloodtype'
        /// </summary>
        [Fact]
        public void BloodtypeTest()
        {
            // TODO unit test for the property 'Bloodtype'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'Genres'
        /// </summary>
        [Fact]
        public void GenresTest()
        {
            // TODO unit test for the property 'Genres'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }
        /// <summary>
        /// Test the property 'Social'
        /// </summary>
        [Fact]
        public void SocialTest()
        {
            // TODO unit test for the property 'Social'
        }
        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Fact]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }
        /// <summary>
        /// Test the property 'LastUpdated'
        /// </summary>
        [Fact]
        public void LastUpdatedTest()
        {
            // TODO unit test for the property 'LastUpdated'
        }
        /// <summary>
        /// Test the property 'AddedBy'
        /// </summary>
        [Fact]
        public void AddedByTest()
        {
            // TODO unit test for the property 'AddedBy'
        }
        /// <summary>
        /// Test the property 'Admin'
        /// </summary>
        [Fact]
        public void AdminTest()
        {
            // TODO unit test for the property 'Admin'
        }

    }

}
