/*
 * MangaUpdates API
 *
 * This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MangaUpdates.Model;
using MangaUpdates.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MangaUpdates.Test.Model
{
    /// <summary>
    ///  Class for testing UserModelV1AdminPermissions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserModelV1AdminPermissionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserModelV1AdminPermissions
        //private UserModelV1AdminPermissions instance;

        public UserModelV1AdminPermissionsTests()
        {
            // TODO uncomment below to create an instance of UserModelV1AdminPermissions
            //instance = new UserModelV1AdminPermissions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserModelV1AdminPermissions
        /// </summary>
        [Fact]
        public void UserModelV1AdminPermissionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserModelV1AdminPermissions
            //Assert.IsType<UserModelV1AdminPermissions>(instance);
        }


        /// <summary>
        /// Test the property 'PAddReleases'
        /// </summary>
        [Fact]
        public void PAddReleasesTest()
        {
            // TODO unit test for the property 'PAddReleases'
        }
        /// <summary>
        /// Test the property 'PEditUsers'
        /// </summary>
        [Fact]
        public void PEditUsersTest()
        {
            // TODO unit test for the property 'PEditUsers'
        }
        /// <summary>
        /// Test the property 'PEditGroups'
        /// </summary>
        [Fact]
        public void PEditGroupsTest()
        {
            // TODO unit test for the property 'PEditGroups'
        }
        /// <summary>
        /// Test the property 'PEditPoll'
        /// </summary>
        [Fact]
        public void PEditPollTest()
        {
            // TODO unit test for the property 'PEditPoll'
        }
        /// <summary>
        /// Test the property 'PEditSeries'
        /// </summary>
        [Fact]
        public void PEditSeriesTest()
        {
            // TODO unit test for the property 'PEditSeries'
        }
        /// <summary>
        /// Test the property 'PEditReviews'
        /// </summary>
        [Fact]
        public void PEditReviewsTest()
        {
            // TODO unit test for the property 'PEditReviews'
        }
        /// <summary>
        /// Test the property 'PEditNews'
        /// </summary>
        [Fact]
        public void PEditNewsTest()
        {
            // TODO unit test for the property 'PEditNews'
        }
        /// <summary>
        /// Test the property 'PEditAffiliates'
        /// </summary>
        [Fact]
        public void PEditAffiliatesTest()
        {
            // TODO unit test for the property 'PEditAffiliates'
        }
        /// <summary>
        /// Test the property 'PEditAboutus'
        /// </summary>
        [Fact]
        public void PEditAboutusTest()
        {
            // TODO unit test for the property 'PEditAboutus'
        }
        /// <summary>
        /// Test the property 'PViewLog'
        /// </summary>
        [Fact]
        public void PViewLogTest()
        {
            // TODO unit test for the property 'PViewLog'
        }
        /// <summary>
        /// Test the property 'PEditConfig'
        /// </summary>
        [Fact]
        public void PEditConfigTest()
        {
            // TODO unit test for the property 'PEditConfig'
        }
        /// <summary>
        /// Test the property 'PViewStats'
        /// </summary>
        [Fact]
        public void PViewStatsTest()
        {
            // TODO unit test for the property 'PViewStats'
        }
        /// <summary>
        /// Test the property 'PEditGenre'
        /// </summary>
        [Fact]
        public void PEditGenreTest()
        {
            // TODO unit test for the property 'PEditGenre'
        }
        /// <summary>
        /// Test the property 'PEditAuthors'
        /// </summary>
        [Fact]
        public void PEditAuthorsTest()
        {
            // TODO unit test for the property 'PEditAuthors'
        }
        /// <summary>
        /// Test the property 'PEditPublishers'
        /// </summary>
        [Fact]
        public void PEditPublishersTest()
        {
            // TODO unit test for the property 'PEditPublishers'
        }
        /// <summary>
        /// Test the property 'PEditPartialUsers'
        /// </summary>
        [Fact]
        public void PEditPartialUsersTest()
        {
            // TODO unit test for the property 'PEditPartialUsers'
        }

    }

}
