/*
 * MangaUpdates API
 *
 * This API powers our website. Most API functions are public and do not require an account. For user-based functions, you must register an account. Currently, user registration must be done through our main website and is disabled via this API.  Download OpenAPI Specification: [openapi.yaml](openapi.yaml)  Please contact us at the following emails if you have questions:  * lambchopsil@mangaupdates.com * manick@mangaupdates.com  ## Warranties  MangaUpdates makes no warranties about service availability, correctness of the data, or anything else. The service is provided as is, and may change at any time.  ## Acceptable Use Policy  * You will credit MangaUpdates when using data provided by this API. * You will use reasonable spacing between requests so as not to overwhelm the MangaUpdates servers, and employ caching mechanisms when accessing data. * You will NOT use MangaUpdates data or API in a way that will:     * Deceive or defraud users     * Assist or perform an illegal action     * Create spam     * Damage the database  We reserve the right to change this policy at any time.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MangaUpdates.Model;
using MangaUpdates.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MangaUpdates.Test.Model
{
    /// <summary>
    ///  Class for testing UserModelSearchV1Stats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserModelSearchV1StatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserModelSearchV1Stats
        //private UserModelSearchV1Stats instance;

        public UserModelSearchV1StatsTests()
        {
            // TODO uncomment below to create an instance of UserModelSearchV1Stats
            //instance = new UserModelSearchV1Stats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserModelSearchV1Stats
        /// </summary>
        [Fact]
        public void UserModelSearchV1StatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserModelSearchV1Stats
            //Assert.IsType<UserModelSearchV1Stats>(instance);
        }


        /// <summary>
        /// Test the property 'ForumPosts'
        /// </summary>
        [Fact]
        public void ForumPostsTest()
        {
            // TODO unit test for the property 'ForumPosts'
        }
        /// <summary>
        /// Test the property 'AddedAuthors'
        /// </summary>
        [Fact]
        public void AddedAuthorsTest()
        {
            // TODO unit test for the property 'AddedAuthors'
        }
        /// <summary>
        /// Test the property 'AddedGroups'
        /// </summary>
        [Fact]
        public void AddedGroupsTest()
        {
            // TODO unit test for the property 'AddedGroups'
        }
        /// <summary>
        /// Test the property 'AddedPublishers'
        /// </summary>
        [Fact]
        public void AddedPublishersTest()
        {
            // TODO unit test for the property 'AddedPublishers'
        }
        /// <summary>
        /// Test the property 'AddedReleases'
        /// </summary>
        [Fact]
        public void AddedReleasesTest()
        {
            // TODO unit test for the property 'AddedReleases'
        }
        /// <summary>
        /// Test the property 'AddedSeries'
        /// </summary>
        [Fact]
        public void AddedSeriesTest()
        {
            // TODO unit test for the property 'AddedSeries'
        }

    }

}
